-- MySQL Script generated by MySQL Workbench
-- 2020-01-24 04:54:23 +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE SCHEMA IF NOT EXISTS `dss` DEFAULT CHARACTER SET latin1 ;
USE `dss` ;

-- -----------------------------------------------------
-- Table `dss`.`accuracy_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`accuracy_rules` ;

CREATE TABLE IF NOT EXISTS `dss`.`accuracy_rules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `model_type` VARCHAR(45) NULL DEFAULT NULL,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `observed_stations` VARCHAR(250) NULL DEFAULT NULL,
  `allowed_error` FLOAT NULL DEFAULT '0',
  `rule_accuracy` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`dynamic_dags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`dynamic_dags` ;

CREATE TABLE IF NOT EXISTS `dss`.`dynamic_dags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dag_name` VARCHAR(45) NULL DEFAULT NULL,
  `schedule` VARCHAR(45) NULL DEFAULT NULL,
  `timeout` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `last_trigger_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`dynamic_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`dynamic_tasks` ;

CREATE TABLE IF NOT EXISTS `dss`.`dynamic_tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NOT NULL,
  `bash_script` VARCHAR(100) NOT NULL,
  `input_params` VARCHAR(250) NULL DEFAULT NULL,
  `timeout` VARCHAR(100) NOT NULL,
  `task_order` INT(11) NULL DEFAULT NULL,
  `active` TINYINT(2) NULL DEFAULT NULL,
  `dag_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`flo2d_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`flo2d_rules` ;

CREATE TABLE IF NOT EXISTS `dss`.`flo2d_rules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL COMMENT '0 - disable, 1 - enable, 2 - running, 3 - completed',
  `target_model` VARCHAR(45) NULL DEFAULT NULL,
  `forecast_days` INT(11) NULL DEFAULT NULL,
  `observed_days` INT(11) NULL DEFAULT NULL,
  `no_forecast_continue` TINYINT(1) NULL DEFAULT NULL,
  `no_observed_continue` TINYINT(1) NULL DEFAULT NULL,
  `raincell_data_from` INT(11) NULL DEFAULT NULL,
  `inflow_data_from` INT(11) NULL DEFAULT NULL,
  `outflow_data_from` INT(11) NULL DEFAULT NULL,
  `ignore_previous_run` TINYINT(1) NULL DEFAULT NULL,
  `accuracy_rule` INT(11) NULL DEFAULT '0',
  `current_accuracy` FLOAT NULL DEFAULT '0',
  `rule_details` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`hechms_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`hechms_rules` ;

CREATE TABLE IF NOT EXISTS `dss`.`hechms_rules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL COMMENT '0 - disable, 1 - enable, 2 - running, 3 - completed',
  `target_model` VARCHAR(45) NULL DEFAULT NULL,
  `forecast_days` INT(11) NULL DEFAULT NULL,
  `observed_days` INT(11) NULL DEFAULT NULL,
  `init_run` TINYINT(1) NULL DEFAULT NULL,
  `no_forecast_continue` TINYINT(1) NULL DEFAULT NULL,
  `no_observed_continue` TINYINT(1) NULL DEFAULT NULL,
  `rainfall_data_from` INT(11) NULL DEFAULT NULL,
  `ignore_previous_run` TINYINT(1) NULL DEFAULT NULL,
  `accuracy_rule` INT(11) NULL DEFAULT '0',
  `current_accuracy` FLOAT NULL DEFAULT '0',
  `rule_details` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`namelist_input_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`namelist_input_config` ;

CREATE TABLE IF NOT EXISTS `dss`.`namelist_input_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `run_days` INT(11) NULL DEFAULT NULL,
  `run_hours` INT(11) NULL DEFAULT NULL,
  `run_minutes` INT(11) NULL DEFAULT NULL,
  `run_seconds` INT(11) NULL DEFAULT NULL,
  `interval_seconds` INT(11) NULL DEFAULT NULL,
  `input_from_file` VARCHAR(45) NULL DEFAULT NULL,
  `history_interval` VARCHAR(45) NULL DEFAULT NULL,
  `frames_per_outfile` VARCHAR(45) NULL DEFAULT NULL,
  `restart` VARCHAR(45) NULL DEFAULT NULL,
  `restart_interval` INT(11) NULL DEFAULT NULL,
  `io_form_history` INT(11) NULL DEFAULT NULL,
  `io_form_restart` INT(11) NULL DEFAULT NULL,
  `io_form_input` INT(11) NULL DEFAULT NULL,
  `io_form_boundary` INT(11) NULL DEFAULT NULL,
  `debug_level` INT(11) NULL DEFAULT NULL,
  `time_step` INT(11) NULL DEFAULT NULL,
  `time_step_fract_num` INT(11) NULL DEFAULT NULL,
  `time_step_fract_den` INT(11) NULL DEFAULT NULL,
  `max_dom` INT(11) NULL DEFAULT NULL,
  `e_we` VARCHAR(45) NULL DEFAULT NULL,
  `e_sn` VARCHAR(45) NULL DEFAULT NULL,
  `e_vert` VARCHAR(45) NULL DEFAULT NULL,
  `p_top_requested` INT(11) NULL DEFAULT NULL,
  `num_metgrid_levels` INT(11) NULL DEFAULT NULL,
  `num_metgrid_soil_levels` INT(11) NULL DEFAULT NULL,
  `dx` VARCHAR(45) NULL DEFAULT NULL,
  `dy` VARCHAR(45) NULL DEFAULT NULL,
  `grid_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_id` VARCHAR(45) NULL DEFAULT NULL,
  `i_parent_start` VARCHAR(45) NULL DEFAULT NULL,
  `j_parent_start` VARCHAR(45) NULL DEFAULT NULL,
  `parent_grid_ratio` VARCHAR(45) NULL DEFAULT NULL,
  `parent_time_step_ratio` VARCHAR(45) NULL DEFAULT NULL,
  `feedback` INT(11) NULL DEFAULT NULL,
  `smooth_option` INT(11) NULL DEFAULT NULL,
  `mp_physics` VARCHAR(45) NULL DEFAULT NULL,
  `ra_lw_physics` VARCHAR(45) NULL DEFAULT NULL,
  `ra_sw_physics` VARCHAR(45) NULL DEFAULT NULL,
  `radt` VARCHAR(45) NULL DEFAULT NULL,
  `sf_sfclay_physics` VARCHAR(45) NULL DEFAULT NULL,
  `sf_surface_physics` VARCHAR(45) NULL DEFAULT NULL,
  `bl_pbl_physics` VARCHAR(45) NULL DEFAULT NULL,
  `bldt` VARCHAR(45) NULL DEFAULT NULL,
  `cu_physics` VARCHAR(45) NULL DEFAULT NULL,
  `cudt` VARCHAR(45) NULL DEFAULT NULL,
  `isfflx` INT(11) NULL DEFAULT NULL,
  `ifsnow` INT(11) NULL DEFAULT NULL,
  `icloud` INT(11) NULL DEFAULT NULL,
  `surface_input_source` INT(11) NULL DEFAULT NULL,
  `num_soil_layers` INT(11) NULL DEFAULT NULL,
  `sf_urban_physics` VARCHAR(45) NULL DEFAULT NULL,
  `w_damping` INT(11) NULL DEFAULT NULL,
  `diff_opt` INT(11) NULL DEFAULT NULL,
  `km_opt` INT(11) NULL DEFAULT NULL,
  `diff_6th_opt` VARCHAR(45) NULL DEFAULT NULL,
  `diff_6th_factor` VARCHAR(45) NULL DEFAULT NULL,
  `base_temp` INT(11) NULL DEFAULT NULL,
  `damp_opt` INT(11) NULL DEFAULT NULL,
  `epssm` FLOAT NULL DEFAULT NULL,
  `zdamp` VARCHAR(45) NULL DEFAULT NULL,
  `dampcoef` VARCHAR(45) NULL DEFAULT NULL,
  `khdif` VARCHAR(45) NULL DEFAULT NULL,
  `kvdif` VARCHAR(45) NULL DEFAULT NULL,
  `non_hydrostatic` VARCHAR(45) NULL DEFAULT NULL,
  `moist_adv_opt` VARCHAR(45) NULL DEFAULT NULL,
  `scalar_adv_opt` VARCHAR(45) NULL DEFAULT NULL,
  `spec_bdy_width` INT(11) NULL DEFAULT NULL,
  `spec_zone` INT(11) NULL DEFAULT NULL,
  `relax_zone` INT(11) NULL DEFAULT NULL,
  `specified` VARCHAR(45) NULL DEFAULT NULL,
  `nested` VARCHAR(45) NULL DEFAULT NULL,
  `nio_tasks_per_group` INT(11) NULL DEFAULT NULL,
  `nio_groups` INT(11) NULL DEFAULT NULL,
  `last_access_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`namelist_wps_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`namelist_wps_config` ;

CREATE TABLE IF NOT EXISTS `dss`.`namelist_wps_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `wrf_core` VARCHAR(45) NULL DEFAULT NULL,
  `max_dom` INT(11) NULL DEFAULT NULL,
  `interval_seconds` INT(11) NULL DEFAULT NULL,
  `io_form_geogrid` INT(11) NULL DEFAULT NULL,
  `parent_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_grid_ratio` VARCHAR(45) NULL DEFAULT NULL,
  `i_parent_start` VARCHAR(45) NULL DEFAULT NULL,
  `j_parent_start` VARCHAR(45) NULL DEFAULT NULL,
  `e_we` VARCHAR(45) NULL DEFAULT NULL,
  `e_sn` VARCHAR(45) NULL DEFAULT NULL,
  `geog_data_res` VARCHAR(45) NULL DEFAULT NULL,
  `dx` VARCHAR(45) NULL DEFAULT NULL,
  `dy` VARCHAR(45) NULL DEFAULT NULL,
  `map_proj` VARCHAR(45) NULL DEFAULT NULL,
  `ref_lat` FLOAT NULL DEFAULT NULL,
  `ref_lon` FLOAT NULL DEFAULT NULL,
  `truelat1` FLOAT NULL DEFAULT NULL,
  `truelat2` FLOAT NULL DEFAULT NULL,
  `stand_lon` FLOAT NULL DEFAULT NULL,
  `geog_data_path` VARCHAR(45) NULL DEFAULT NULL,
  `out_format` VARCHAR(45) NULL DEFAULT NULL,
  `prefix` VARCHAR(45) NULL DEFAULT NULL,
  `fg_name` VARCHAR(45) NULL DEFAULT NULL,
  `io_form_metgrid` INT(11) NULL DEFAULT NULL,
  `last_access_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`pump_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`pump_rules` ;

CREATE TABLE IF NOT EXISTS `dss`.`pump_rules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rule_name` VARCHAR(45) NULL DEFAULT NULL,
  `rule_logic` VARCHAR(5000) NULL DEFAULT NULL,
  `dag_name` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `schedule` VARCHAR(45) NULL DEFAULT NULL,
  `last_trigger_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`rule_variables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`rule_variables` ;

CREATE TABLE IF NOT EXISTS `dss`.`rule_variables` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(45) NOT NULL,
  `variable_type` VARCHAR(45) NOT NULL,
  `current_rainfall` FLOAT NULL DEFAULT NULL,
  `current_water_level` FLOAT NULL DEFAULT NULL,
  `alert_water_level` FLOAT NULL DEFAULT NULL,
  `warning_water_level` FLOAT NULL DEFAULT NULL,
  `water_level_rising_rate` FLOAT NULL DEFAULT NULL,
  `rainfall_intensity` FLOAT NULL DEFAULT NULL,
  `last_1_day_rainfall` FLOAT NULL DEFAULT NULL,
  `last_2_day_rainfall` FLOAT NULL DEFAULT NULL,
  `last_3_day_rainfall` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `location_name`, `variable_type`),
  UNIQUE INDEX `station_UNIQUE` (`location_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`variable_routines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`variable_routines` ;

CREATE TABLE IF NOT EXISTS `dss`.`variable_routines` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `variable_name` VARCHAR(45) NULL DEFAULT NULL,
  `variable_type` VARCHAR(45) NULL DEFAULT NULL,
  `dag_name` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `schedule` VARCHAR(45) NULL DEFAULT NULL,
  `last_trigger_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`workflow_routines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`workflow_routines` ;

CREATE TABLE IF NOT EXISTS `dss`.`workflow_routines` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dss1` INT(11) NULL DEFAULT NULL COMMENT 'rule id related to wrf',
  `dss2` INT(11) NULL DEFAULT NULL COMMENT 'rule id related to hechms',
  `dss3` INT(11) NULL DEFAULT NULL COMMENT 'rule id related to flo2d',
  `status` INT(11) NULL DEFAULT NULL COMMENT '0-not triggered, 1- triggered, 2- running, 3- completed, 4- error',
  `cascade_on` TINYINT(1) NULL DEFAULT NULL,
  `schedule` VARCHAR(45) NULL DEFAULT NULL,
  `last_trigger_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dss`.`wrf_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dss`.`wrf_rules` ;

CREATE TABLE IF NOT EXISTS `dss`.`wrf_rules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL COMMENT '0 - disable, 1 - enable, 2 - running, 3 - completed',
  `target_model` VARCHAR(45) NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `run` VARCHAR(45) NULL DEFAULT NULL,
  `hour` VARCHAR(45) NULL DEFAULT NULL,
  `ignore_previous_run` TINYINT(1) NULL DEFAULT NULL,
  `check_gfs_data_availability` TINYINT(1) NULL DEFAULT NULL,
  `accuracy_rule` INT(11) NULL DEFAULT '0',
  `current_accuracy` FLOAT NULL DEFAULT '0',
  `rule_details` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;
